ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        sslPort = 8443
        sslPort = ${?SSL_PORT}
    }
    application {
        modules = [ io.github.devapro.droid.sync.ApplicationKt.module ]
    }
    security {
        ssl {
            keyStore = "certs/keystore.jks"
            keyStore = ${?KEYSTORE_PATH}
            keyAlias = "droidpasswords"
            keyAlias = ${?KEY_ALIAS}
            keyStorePassword = "changeit"
            keyStorePassword = ${?KEYSTORE_PASSWORD}
            privateKeyPassword = "changeit"
            privateKeyPassword = ${?KEY_PASSWORD}
        }
    }
}
